# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./homography-app
    ports:
      - "8080:80" #Port 8080 on the host linked to 80 of nginx's server
    restart: always
    depends_on:
      - backend
    environment:
    - CHOKIDAR_USEPOLLING=true 
    stdin_open: true              # Keep STDIN open
    tty: true      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
