# homography-app/Dockerfile
FROM node:16-alpine as build

# Set the working directory
WORKDIR /app

# Copy only package.json and package-lock.json initially for caching
COPY package.json package-lock.json ./
RUN npm install

# Copy the React app source code
COPY . .

RUN npm run build

#Serve with nginx
FROM nginx:alpine

# Copy the build output from the previous stage to the Nginx html directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose the Nginx default HTTP port
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]